name: tasky_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  http: ^1.3.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.7
  go_router: ^15.1.1
  table_calendar: ^3.0.9
  pie_chart: ^5.3.2
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  json_annotation: ^4.6.0


  # ✅ Version stable pour mobile uniquement (Android/iOS)
  file_picker: ^5.3.4

  # 📂 Pour ouvrir les fichiers (PDF, etc.)
  open_file: ^3.2.1
  open_filex: ^4.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.8
  build_runner: ^2.1.10
  json_serializable: ^6.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/inspirant.png
    - assets/images/istock.jpg
